name: Build the system and run tests
on:
  push:
    branches: [ trunk ]
  pull_request:
    branches: [ trunk ]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cc: [gcc, clang]
    steps:
    - name: Checkout repository
      uses: actions/checkout@main
    - name: Build the system
      run: make sys
      env:
        CC: ${{ matrix.cc }}
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cc: [gcc, clang]
    steps:
    - name: Checkout repository
      uses: actions/checkout@main
    - name: Build the system
      run: make sys
      env:
        CC: ${{ matrix.cc }}
    - name: Run system tests
      run: make test
      env:
        CC: ${{ matrix.cc }}
