name: build
on:
  push:
    branches: [trunk]
  pull_request:
    branches: [trunk]
jobs:
  build-lib:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        cc: [gcc, clang]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@main
    - name: Build library sources
      run: make lib
      env:
        CC: ${{ matrix.cc }}
