name: build
on:
  push:
    branches: [trunk]
  pull_request:
    branches: [trunk]
jobs:
  sys:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@main
    - name: Lint headers and source code
      run: make lint
