name: test
on: [push, pull_request]
jobs:
  test-lib:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        cc: [gcc, clang]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@main
    - name: Run library tests
      run: make lib_test
      env:
        CC: ${{ matrix.cc }}
